# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7711cd4ac77012b099928f7a7a2aae4d10d1afb9834639521ead73cda1f0805ca08281442182cdbb5c4e7f828b60cc4e407b5a17d37c9dff4064624b7f8719a

test:
  secret_key_base: 22909d725096418e5894c643cc1dabef05c1faa6108bd4afd823b2455fdbab1d04874bd822cc59a9c566978dcaeebeffc7305af0b8554a43af40783dc24affb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
